package Estudiantes;

import javax.swing.JOptionPane;

public class vistaEstudiantes extends javax.swing.JFrame {

    private GestionEstudiantes gestionEstudiantes;

    public vistaEstudiantes() {
        initComponents();
        gestionEstudiantes = new GestionEstudiantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEstudiante = new javax.swing.JLabel();
        lbCedulaEstudiante = new javax.swing.JLabel();
        lbNombreEstudiante = new javax.swing.JLabel();
        lbApellidoEstudiante = new javax.swing.JLabel();
        lbCarreraEstudiante = new javax.swing.JLabel();
        lbDireccionEstudiante = new javax.swing.JLabel();
        BotonGuardarEstu = new javax.swing.JButton();
        BotonModificarEstu = new javax.swing.JButton();
        BotonBorrarEstu = new javax.swing.JButton();
        BotonConsultarEstu = new javax.swing.JButton();
        TextFieldCedulaEstu = new javax.swing.JTextField();
        TextFieldNombreEstu = new javax.swing.JTextField();
        TextFieldApellidoEstu = new javax.swing.JTextField();
        TextFieldCarreraEstu = new javax.swing.JTextField();
        TextFieldDireccionEstu = new javax.swing.JTextField();
        lbtelefonoEstu = new javax.swing.JLabel();
        TextFieldTelefonoEstu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbEstudiante.setText("Estudiantes");

        lbCedulaEstudiante.setText("Cedula");

        lbNombreEstudiante.setText("Nombre");

        lbApellidoEstudiante.setText("Apellido");

        lbCarreraEstudiante.setText("Carrera");

        lbDireccionEstudiante.setText("Direccion");

        BotonGuardarEstu.setText("Guardar");
        BotonGuardarEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarEstuActionPerformed(evt);
            }
        });

        BotonModificarEstu.setText("Modificar");
        BotonModificarEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarEstuActionPerformed(evt);
            }
        });

        BotonBorrarEstu.setText("Borrar");
        BotonBorrarEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarEstuActionPerformed(evt);
            }
        });

        BotonConsultarEstu.setText("Consultar");
        BotonConsultarEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarEstuActionPerformed(evt);
            }
        });

        TextFieldCedulaEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCedulaEstuActionPerformed(evt);
            }
        });

        TextFieldApellidoEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldApellidoEstuActionPerformed(evt);
            }
        });

        lbtelefonoEstu.setText("Telefono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(BotonGuardarEstu)
                            .addGap(12, 12, 12)
                            .addComponent(BotonModificarEstu)
                            .addGap(18, 18, 18)
                            .addComponent(BotonBorrarEstu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BotonConsultarEstu))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbtelefonoEstu)
                                        .addComponent(lbDireccionEstudiante)
                                        .addComponent(lbCarreraEstudiante)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbCedulaEstudiante)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbNombreEstudiante)
                                            .addComponent(lbApellidoEstudiante)))))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldApellidoEstu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldTelefonoEstu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldDireccionEstu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldCarreraEstu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldNombreEstu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldCedulaEstu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(116, 116, 116)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lbEstudiante)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbEstudiante)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCedulaEstudiante)
                    .addComponent(TextFieldCedulaEstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreEstudiante)
                    .addComponent(TextFieldNombreEstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellidoEstudiante)
                    .addComponent(TextFieldApellidoEstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCarreraEstudiante)
                    .addComponent(TextFieldCarreraEstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccionEstudiante)
                    .addComponent(TextFieldDireccionEstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtelefonoEstu)
                    .addComponent(TextFieldTelefonoEstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonConsultarEstu)
                    .addComponent(BotonBorrarEstu)
                    .addComponent(BotonModificarEstu)
                    .addComponent(BotonGuardarEstu))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonGuardarEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarEstuActionPerformed
        String codigo = TextFieldCedulaEstu.getText().trim();
        String nombres = TextFieldNombreEstu.getText().trim();
        String apellidos = TextFieldApellidoEstu.getText().trim();
        String carrera = TextFieldCarreraEstu.getText().trim();
        String direccion = TextFieldDireccionEstu.getText().trim();
        String telefono = TextFieldTelefonoEstu.getText().trim();

        // Validar que todos los campos estén llenos
        if (codigo.isEmpty() || nombres.isEmpty() || apellidos.isEmpty() || carrera.isEmpty()
                || direccion.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el estudiante
        Estudiante estudiante = new Estudiante();
        estudiante.setNombres(nombres);
        estudiante.setApellidos(apellidos);
        estudiante.setCarrera(carrera);
        estudiante.setDireccion(direccion);
        estudiante.setTelefono(telefono);

        // Insertar el estudiante usando la lógica de gestionEstudiantes
        if (gestionEstudiantes.insertarEstudiante(codigo, estudiante)) {
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Estudiante guardado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "El estudiante con el código " + codigo + " ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonGuardarEstuActionPerformed

    private void BotonConsultarEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarEstuActionPerformed
        ConsultaDialog consultaDialog = new ConsultaDialog(this, gestionEstudiantes);
        consultaDialog.setVisible(true);
    }//GEN-LAST:event_BotonConsultarEstuActionPerformed

    private void TextFieldCedulaEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCedulaEstuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCedulaEstuActionPerformed

    private void TextFieldApellidoEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldApellidoEstuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldApellidoEstuActionPerformed

    private void BotonBorrarEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarEstuActionPerformed
        BorrarDialog borrarDialog = new BorrarDialog(this, gestionEstudiantes);
        borrarDialog.setVisible(true);
    }//GEN-LAST:event_BotonBorrarEstuActionPerformed

    private void BotonModificarEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarEstuActionPerformed
        ModificarDialog modificarDialog = new ModificarDialog(this, gestionEstudiantes);
        modificarDialog.setVisible(true);
    }//GEN-LAST:event_BotonModificarEstuActionPerformed
    private void limpiarCampos() {
        TextFieldCedulaEstu.setText("");
        TextFieldNombreEstu.setText("");
        TextFieldApellidoEstu.setText("");
        TextFieldCarreraEstu.setText("");
        TextFieldDireccionEstu.setText("");
        TextFieldTelefonoEstu.setText("");
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(vistaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Crear e iniciar la ventana de vistaEstudiantes
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new vistaEstudiantes().setVisible(true);
        }
    });
}

    //</editor-fold>


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrarEstu;
    private javax.swing.JButton BotonConsultarEstu;
    private javax.swing.JButton BotonGuardarEstu;
    private javax.swing.JButton BotonModificarEstu;
    private javax.swing.JTextField TextFieldApellidoEstu;
    private javax.swing.JTextField TextFieldCarreraEstu;
    private javax.swing.JTextField TextFieldCedulaEstu;
    private javax.swing.JTextField TextFieldDireccionEstu;
    private javax.swing.JTextField TextFieldNombreEstu;
    private javax.swing.JTextField TextFieldTelefonoEstu;
    private javax.swing.JLabel lbApellidoEstudiante;
    private javax.swing.JLabel lbCarreraEstudiante;
    private javax.swing.JLabel lbCedulaEstudiante;
    private javax.swing.JLabel lbDireccionEstudiante;
    private javax.swing.JLabel lbEstudiante;
    private javax.swing.JLabel lbNombreEstudiante;
    private javax.swing.JLabel lbtelefonoEstu;
    // End of variables declaration//GEN-END:variables
}
