package profesores;

import Estudiantes.Estudiante;
import javax.swing.JOptionPane;

public class vistaProfesores extends javax.swing.JFrame {

    private GestionProfesores gestionProfesores;

    public vistaProfesores() {
        initComponents();
        gestionProfesores = new GestionProfesores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonBorrarProf = new javax.swing.JButton();
        BotonConsultarProf = new javax.swing.JButton();
        TextFieldCedulaProf = new javax.swing.JTextField();
        TextFieldNombreProf = new javax.swing.JTextField();
        TextFieldApellidoProf = new javax.swing.JTextField();
        TextFieldCarreraProf = new javax.swing.JTextField();
        TextFieldDireccionProf = new javax.swing.JTextField();
        lbtelefonoProf = new javax.swing.JLabel();
        TextFieldTelefonoProf = new javax.swing.JTextField();
        lbProfesor = new javax.swing.JLabel();
        lbCedulaProf = new javax.swing.JLabel();
        lbNombreProf = new javax.swing.JLabel();
        lbApellidoProf = new javax.swing.JLabel();
        lbCarreraProf = new javax.swing.JLabel();
        lbDireccionProf = new javax.swing.JLabel();
        BotonGuardarProf = new javax.swing.JButton();
        BotonModificarProf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonBorrarProf.setText("Borrar");
        BotonBorrarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarProfActionPerformed(evt);
            }
        });

        BotonConsultarProf.setText("Consultar");
        BotonConsultarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarProfActionPerformed(evt);
            }
        });

        TextFieldCedulaProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCedulaProfActionPerformed(evt);
            }
        });

        TextFieldApellidoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldApellidoProfActionPerformed(evt);
            }
        });

        lbtelefonoProf.setText("Telefono");

        lbProfesor.setText("Profesores");

        lbCedulaProf.setText("Cedula");

        lbNombreProf.setText("Nombre");

        lbApellidoProf.setText("Apellido");

        lbCarreraProf.setText("Carrera");

        lbDireccionProf.setText("Direccion");

        BotonGuardarProf.setText("Guardar");
        BotonGuardarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarProfActionPerformed(evt);
            }
        });

        BotonModificarProf.setText("Modificar");
        BotonModificarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(BotonGuardarProf)
                            .addGap(12, 12, 12)
                            .addComponent(BotonModificarProf)
                            .addGap(18, 18, 18)
                            .addComponent(BotonBorrarProf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BotonConsultarProf))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbtelefonoProf)
                                        .addComponent(lbDireccionProf)
                                        .addComponent(lbCarreraProf)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbCedulaProf)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbNombreProf)
                                            .addComponent(lbApellidoProf)))))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldApellidoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldTelefonoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldDireccionProf, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldCarreraProf, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldNombreProf, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldCedulaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(116, 116, 116)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lbProfesor)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbProfesor)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCedulaProf)
                    .addComponent(TextFieldCedulaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreProf)
                    .addComponent(TextFieldNombreProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellidoProf)
                    .addComponent(TextFieldApellidoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCarreraProf)
                    .addComponent(TextFieldCarreraProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccionProf)
                    .addComponent(TextFieldDireccionProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtelefonoProf)
                    .addComponent(TextFieldTelefonoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonConsultarProf)
                    .addComponent(BotonBorrarProf)
                    .addComponent(BotonModificarProf)
                    .addComponent(BotonGuardarProf))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBorrarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarProfActionPerformed
        BorrarDialog borrarDialog = new BorrarDialog(this, gestionProfesores);
        borrarDialog.setVisible(true);
    }//GEN-LAST:event_BotonBorrarProfActionPerformed

    private void BotonConsultarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarProfActionPerformed
        ConsultaDialog consultaDialog = new ConsultaDialog(this, gestionProfesores);
        consultaDialog.setVisible(true);
    }//GEN-LAST:event_BotonConsultarProfActionPerformed

    private void TextFieldCedulaProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCedulaProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCedulaProfActionPerformed

    private void TextFieldApellidoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldApellidoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldApellidoProfActionPerformed

    private void BotonGuardarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarProfActionPerformed
        String codigo = TextFieldCedulaProf.getText().trim();
        String nombres = TextFieldNombreProf.getText().trim();
        String apellidos = TextFieldApellidoProf.getText().trim();
        String carrera = TextFieldCarreraProf.getText().trim();
        String direccion = TextFieldDireccionProf.getText().trim();
        String telefono = TextFieldTelefonoProf.getText().trim();

        // Validar que todos los campos estén llenos
        if (codigo.isEmpty() || nombres.isEmpty() || apellidos.isEmpty() || carrera.isEmpty()
                || direccion.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el estudiante
        Profesor profesor = new Profesor();
        profesor.setNombres(nombres);
        profesor.setApellidos(apellidos);
        profesor.setCarrera(carrera);
        profesor.setDireccion(direccion);
        profesor.setTelefono(telefono);

        // Insertar el estudiante usando la lógica de gestionEstudiantes
        if (gestionProfesores.insertarEstudiante(codigo, profesor)) {
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Estudiante guardado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "El estudiante con el código " + codigo + " ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonGuardarProfActionPerformed

    private void BotonModificarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarProfActionPerformed
        ModificarDialog modificarDialog = new ModificarDialog(this, gestionProfesores);
        modificarDialog.setVisible(true);
    }//GEN-LAST:event_BotonModificarProfActionPerformed
    private void limpiarCampos() {
        TextFieldCedulaProf.setText("");
        TextFieldNombreProf.setText("");
        TextFieldApellidoProf.setText("");
        TextFieldCarreraProf.setText("");
        TextFieldDireccionProf.setText("");
        TextFieldTelefonoProf.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaProfesores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrarProf;
    private javax.swing.JButton BotonConsultarProf;
    private javax.swing.JButton BotonGuardarProf;
    private javax.swing.JButton BotonModificarProf;
    private javax.swing.JTextField TextFieldApellidoProf;
    private javax.swing.JTextField TextFieldCarreraProf;
    private javax.swing.JTextField TextFieldCedulaProf;
    private javax.swing.JTextField TextFieldDireccionProf;
    private javax.swing.JTextField TextFieldNombreProf;
    private javax.swing.JTextField TextFieldTelefonoProf;
    private javax.swing.JLabel lbApellidoProf;
    private javax.swing.JLabel lbCarreraProf;
    private javax.swing.JLabel lbCedulaProf;
    private javax.swing.JLabel lbDireccionProf;
    private javax.swing.JLabel lbNombreProf;
    private javax.swing.JLabel lbProfesor;
    private javax.swing.JLabel lbtelefonoProf;
    // End of variables declaration//GEN-END:variables
}
